name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setting up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setting up Maven
        run: sudo apt-get install maven

      - name: Build the project with Maven
        run: mvn clean install -U

      - name: SCP SSH Pipeline
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          scp: |
            ./target/*.war => /tmp/
          last_ssh: |
            ls -lart /tmp
      - name: Invoke Jenkins Deployment Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://${{ secrets.HOST }}:8080"
          user: "admin"
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "DeployToTomcat"
